#pragma once

#include <iostream>
#include <vector>
#include <cstdint>
#include <iomanip>


namespace hnswlib {


// ── Bit layout ────────────────────────────────────────────────
//  bits [0..23]  → id  (24 bits, 23 boolean metadata for filtering)
//  bits [24..63] → X

/*
64-Bit Unified Scalar Label Layout:
┌───────────────────────────────────────┬───────────────────────────────────────┐
│       24-Bit Metadata Bitmask         │        40-Bit Dense Vector ID         │
│     (Upper Bits: 40 to 63)            │         (Lower Bits: 0 to 39)         │
├───────────────────────────────────────┼───────────────────────────────────────┤
│ 00000000 00000000 00000000            │ 00000000 00000000 ... 0000000000000001│
└───────────────────────────────────────┴───────────────────────────────────────┘
▲                                       ▲
│                                       │
└── Category Flags, Visibility Controls, └── Flat Identifier Map to Lexical Object
and Linguistic Locales                  Store (~1.09 Trillion Capacity)

*/


// 40 bits for the unique record ID space (~1 Trillion items)
constexpr uint8_t  _ID_BITS = 40;
constexpr uint64_t _ID_MASK = (1ULL << _ID_BITS) - 1; // 0x000000FFFFFFFFFF


/*
// Look for English docs (0x01) on Core Engine (0x01) with Public access (0x00)
// This evaluates out to a target configuration of 0x0001000100... shifted high
uint64_t runtime_mask  = 0xFFFFFF0000000000; // Track top 24 bits
uint64_t runtime_flags = 0x0001040100000000; // Target criteria bits

MetaMaskFilter query_filter(runtime_mask, runtime_flags);

// Query the index graph passing our functor reference directly
auto result_heap = index->searchKnn(query_vector.data(), k_neighbors, &query_filter);

*/


/**
 * @brief Combines a 40-bit unique vector ID and high-shifted 24-bit metadata flags into a single label.
 * @param unique_id   The sequential record increment index (e.g. 0, 1, 2, 3...)
 * @param scope_bits  The high-shifted metadata bits generated by your IndexScope/TargetScope configuration
 */
inline labeltype make_label(uint64_t unique_id, uint64_t scope_bits = 0) {
    // 1. Isolate the lower 40 bits of the unique record ID to prevent spillover
    uint64_t clean_id = unique_id & _ID_MASK;

    // 2. Merge it with your scope bits (which are already shifted high into bits 40-63)
    return static_cast<hnswlib::labeltype>(scope_bits | clean_id);
}


/**
 * @brief Extracts the unique, incremental record ID from the lower 40 bits.
 * (This is what you previously referred to as 'x')
 */
inline uint64_t label_id(hnswlib::labeltype label) { 
    return static_cast<uint64_t>(label) & _ID_MASK; 
}

/**
 * @brief Extracts the raw, shifted metadata flag block from the upper 24 bits.
 */
inline uint64_t label_metadata(hnswlib::labeltype label) { 
    return static_cast<uint64_t>(label) >> _ID_BITS; 
}

/**
 * @brief Enterprise Metadata Filter hooked into the native hnswlib engine.
 */
struct MetaMaskFilter : public BaseFilterFunctor {
    uint64_t target_mask;      // Isolates which bit categories we care about
    uint64_t required_flags;   // The explicit bit configuration state we expect

    /**
     * @param mask  Bitmask defining the filter boundary (e.g. 0xFFFFFF0000000000 to isolate the top 24 bits)
     * @param flags The required configuration state for those isolated bits
     */
    MetaMaskFilter(uint64_t mask, uint64_t flags)
        : target_mask(mask), required_flags(flags) {}

    /**
     * @brief Core traversal handler evaluated by HNSW in-flight.
     * @param label The raw 64-bit node scalar identifier tracked inside the graph.
     * @return true  -> Include vector in metric distance calculations
     * @return false -> Skip this node/cluster entirely
     */
    bool operator()(hnswlib::labeltype label) override {
        // Cast the internal hnswlib label safely to our 64-bit layout register
        uint64_t full_label = static_cast<uint64_t>(label);

        // Apply mask and match against configuration requirements
        return (full_label & target_mask) == required_flags;
    }
};

/**
 * @brief Represents a target index file slice, encapsulating its 
 * lexical location, ID, and its 24-bit production metadata bitmask.
 */
struct IndexScope {
    std::string name; // The index file path or identifier
    int id;           // The internal integer ID/tag
    
    // --- New Bitmask Properties ---
    uint64_t category_mask = 0; // The compiled bitmask targeting our fields
    uint64_t metadata_bits = 0; // The actual bit configuration state

    IndexScope() : id(0), category_mask(0), metadata_bits(0) {}
    
    IndexScope(const std::string &filename, int _id = 0) 
        : name(filename), id(_id), category_mask(0), metadata_bits(0) {}

    // Legacy Type Implicit Cast Conversions (Keeps existing code unbroken)
    operator std::string() const { return name; }
    operator int() const         { return id;   }

    IndexScope& operator=(const IndexScope& target) {
        if (this != &target) {
            name          = target.name;
            id            = target.id;
            category_mask = target.category_mask;
            metadata_bits = target.metadata_bits;
        }
        return *this;
    }

    // ─────────────────────────────────────────────────────────────────
    // New Fluent Builder Functions to construct masks safely
    // ─────────────────────────────────────────────────────────────────
    
    /**
     * @brief Adds a metadata attribute constraint to the scope layout.
     * @param bit_offset The starting position (0-23 inside the 24-bit space)
     * @param bit_width  The width of the attribute field in bits
     * @param value      The value to assign to this specific field
     */
    IndexScope& with_attribute(uint8_t bit_offset, uint8_t bit_width, uint64_t value) {
        // Enforce boundary protections inside the 24-bit limit
        if (bit_offset + bit_width > 24) return *this;

        // Create a local field mask (e.g., if width is 4, mask is 0x0F)
        uint64_t field_mask = (1ULL << bit_width) - 1;
        
        // Target bits shifted up into the HNSW 24-bit ceiling zone (bits 40-63)
        uint8_t global_shift = 40 + bit_offset;

        // Layer the target mask zone and value configuration into our tracking registers
        category_mask |= (field_mask << global_shift);
        metadata_bits |= ((value & field_mask) << global_shift);

        return *this;
    }

    // Friends and Streams
    friend std::string operator+(const IndexScope& target, const std::string& other) {
        return target.name + other;
    }

    friend std::ostream& operator<<(std::ostream& os, const IndexScope& target) {
        if (target.id == 0) os << target.name;
        else os << target.name << "(" << target.id << ")";
        return os;
    }
};


/*

// Setup a query target domain using the fluent builder
IndexScope target = IndexScope("documentation_index.hnsw", 42)
    .with_attribute(18, 4, 1)  // Product: Core Engine (Value 1)
    .with_attribute(14, 4, 4)  // Version: v4.x (Value 4)
    .with_attribute(10, 4, 1)  // Locale: English (Value 1)
    .with_attribute(8,  2, 1); // Security: Internal Only (Value 1)


hnswlib::labeltype unified_label = make_label(xx, target.metadata_bits);

// and vida the  MetaMaskFilter!
MetaMaskFilter filter(target.category_mask, target.metadata_bits);


For now we'll just handle category (4-bit)  

IndexScope collection_scope = IndexScope(filename, 0)
        .with_attribute(0, 4, static_cast<uint64_t>(category_id));

    uint64_t xx = 0; //
...
hnswlib::labeltype unified_label = make_label(xx, collection_scope.metadata_bits);

*/


}; // Namespace


#if 0

#include <unordered_map>

/**
 * @brief Simple blueprint for the future metadata tracking schema manager.
 */
class MetadataDictionary {
public:
    // Definition of our rigid layout slots inside the 24-bit space
    struct FieldLayout {
        uint8_t bit_offset;
        uint8_t bit_width;
    };

    const FieldLayout category_field = {0, 4};  // Bits 40-43
    const FieldLayout locale_field   = {4, 4};  // Bits 44-47
    const FieldLayout doc_type_field = {8, 4};  // Bits 48-51

    MetadataDictionary() {
        // Populating the dictionary dynamically or from a config file
        doc_type_map["documentation"] = 1;
        doc_type_map["source_code"]   = 2;
        doc_type_map["api_spec"]      = 3;

        locale_map["en"] = 1;
        locale_map["de"] = 2;
        locale_map["fr"] = 3;
    }

    uint64_t get_doc_type_value(const std::string& type_str) {
        auto it = doc_type_map.find(type_str);
        return (it != doc_type_map.end()) ? it->second : 0;
    }

private:
    std::unordered_map<std::string, uint64_t> doc_type_map;
    std::unordered_map<std::string, uint64_t> locale_map;
};

#endif
